# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mspire-mascot-dat"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John T. Prince"]
  s.date = "2013-03-29"
  s.description = "Reads mascot dat files with gusto for mspire library."
  s.email = "jtprince@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mspire/mascot/dat.rb",
    "lib/mspire/mascot/dat/index.rb",
    "lib/mspire/mascot/dat/peptide.rb",
    "lib/mspire/mascot/dat/query.rb",
    "mspire-mascot-dat.gemspec",
    "spec/mspire/mascot/dat/index_spec.rb",
    "spec/mspire/mascot/dat/peptide_spec.rb",
    "spec/mspire/mascot/dat/query_spec.rb",
    "spec/mspire/mascot/dat_spec.rb",
    "spec/reference/dat_format_reference.md",
    "spec/reference/two_spectra_decoy_F004129.png",
    "spec/reference/two_spectra_no_decoy_F004128.png",
    "spec/spec_helper.rb",
    "spec/testfiles/F004128.dat",
    "spec/testfiles/F004129.dat",
    "spec/testfiles/two_spectra.mgf"
  ]
  s.homepage = "http://github.com/princelab/mspire-mascot-dat"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.0"
  s.summary = "Reads mascot dat files for mspire library."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<elif>, ["~> 0.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<elif>, ["~> 0.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<elif>, ["~> 0.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

